Remove non needed copyright header
eiffel-community/eiffel-remrem pull request #11
Opened 2022-01-10 15:57 UTC by m-linner-ericsson

### Applicable Issues
None

### Description of the Change
Add a introduction description of what REMReM does. The introduction also spells out what REMReM stands for.

* Fix spelling of REMReM
* Remove reference to REMReM shared (not used)

### Alternate Designs
Couldn't find any other better place to put this information.

### Benefits
New readers can understand what REMReM does. The current description did not give that introduction.

### Possible Drawbacks
None that I can think of

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Mattias Linnér mattias.linner@ericsson.com

2022-01-10 16:28 UTC, e-backmark-ericsson approved these changes

2022-01-11 05:28 UTC, SantoshNC68 commented on overview.md
> +For every REMRem component it is needed to create a new release tag in the component's repository on GitHub. Once the tag is created the build for the new release tag will be started when you visit t
REMReM

2022-01-11 05:31 UTC, SantoshNC68 requested changes
Also one more thing, in the architecture diagram it is pointing to shared library, has that been modified ? If not the picture has to be modified to reflect the current behavior.

2022-01-11 09:22 UTC, m-linner-ericsson commented on overview.md
> +For every REMRem component it is needed to create a new release tag in the component's repository on GitHub. Once the tag is created the build for the new release tag will be started when you visit t
Thanks! Fixed in 9f0e2d9

2022-01-11 09:23 UTC, m-linner-ericsson commented
> Also one more thing, in the architecture diagram it is pointing to shared library, has that been modified ? If not the picture has to be modified to reflect the current behavior.

Thanks! Fixed in 9f0e2d9

2022-01-11 10:23 UTC, SantoshNC68 reviewed
Just one more little thing on the diagram, there should be a dotted line for other protocol as well as eiffel-remrem-semantics connecting to eiffel-remrem-protocol-interface.

2022-01-11 10:25 UTC, SantoshNC68 reviewed
Any protocol trying to comply with eiffel should try to create the services based on the eiffel-remrem-protocol-interface.

2022-01-11 13:29 UTC, k-hallen-ericsson approved these changes

2022-01-12 12:39 UTC, m-linner-ericsson commented
@SantoshNC68 In https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/pom.xml#L13 it looks like publish uses both semantics and shared. Same with https://github.com/eiffel-community/eiffel-remrem-generate/blob/master/pom.xml#L14. Is the picture then correct?

2022-01-12 16:56 UTC, SantoshNC68 commented
> @SantoshNC68 In https://github.com/eiffel-community/eiffel-remrem-publish/blob/master/pom.xml#L13 it looks like publish uses both semantics and shared. Same with https://github.com/eiffel-community/eiffel-remrem-generate/blob/master/pom.xml#L14. Is the picture then correct?


The eiffel-remrem-shared earlier used to have the code for protocol interfaces that needed to be extended in eiffel-remrem-semantics, but that has changed and now any protocol that should define its own definition of generate, version, etc needs to extend eiffel-remrem-protocol-interface.

There are left over code like VersionService which is used to identify the semantics/any other versions using endpoints using the VersionService class present in the shared library. But the picture will still remain the same as I suggested that the semantics/other protocols should have a dotted connection to eiffel-remrem-protocol-interface.

2022-01-13 16:02 UTC, m-linner-ericsson commented
@SantoshNC68 I have now in 5e05d85 updated the image. I guess that the POMs for generate and publish need updates?

2022-01-17 04:43 UTC, SantoshNC68 approved these changes

2022-01-17 07:21 UTC, e-backmark-ericsson commented
@SantoshNC68 , will you write issues on generate and publish to update their POMs accordingly? We shouldn't remove the shared repo until all references to it are gone.

2022-01-26 09:23 UTC, merged